export const shopConfig = {
  shop: {
    name: "JonsStore",
    tagline: "Digital Solutions & Services Provider",
    description: "Menyediakan berbagai layanan digital berkualitas tinggi untuk kebutuhan bisnis dan personal Anda",
    logo: "/images/logo.png",
    favicon: "/favicon.ico",
  },
  contact: {
    whatsapp: "6281359123789",
    whatsappBot: "6285185926872",
    telegram: "@jonsstore",
    github: "jonalexanderhere",
    youtube: "JonsStore",
    instagram: "jonsstore",
    whatsappGroup: "https://chat.whatsapp.com/group-link",
    telegramGroup: "https://t.me/group-link",
    whatsappChannel: "https://whatsapp.com/channel/link",
  },
  telegram: {
    botToken: "8171054320:AAH6bl1X78luPjctY5wQ2xxi-LGarS-SsgA",
    chatId: "YOUR_CHAT_ID",
  },
  theme: {
    primaryColor: "#1e40af",
    secondaryColor: "#1f2937", 
    accentColor: "#3b82f6",
    backgroundColor: "#0f172a",
    textColor: "#f8fafc",
  },
}

export const products = [
  {
    id: 1,
    name: "Script Bot WhatsApp Premium",
    category: "Script",
    price: 150000,
    originalPrice: 200000,
    image: "/whatsapp-bot-script-interface.jpg",
    description: "Bot WhatsApp otomatis dengan fitur lengkap untuk bisnis",
    features: ["Auto Reply", "Broadcast Message", "Group Management", "Analytics"],
    stock: 25,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 2,
    name: "Jasa Pembuatan Website",
    category: "Jasa",
    price: 500000,
    originalPrice: 750000,
    image: "/modern-website-development.png",
    description: "Pembuatan website profesional dengan design modern",
    features: ["Responsive Design", "SEO Optimized", "Admin Panel", "Free Hosting 1 Tahun"],
    stock: 10,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: 3,
    name: "Cloud Hosting Premium",
    category: "Hosting",
    price: 75000,
    originalPrice: 100000,
    image: "/cloud-server-hosting.jpg",
    description: "Hosting cloud dengan performa tinggi dan uptime 99.9%",
    features: ["SSD Storage", "Free SSL", "Daily Backup", "24/7 Support"],
    stock: 50,
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 4,
    name: "PPOB Multi Payment",
    category: "PPOB",
    price: 300000,
    originalPrice: 400000,
    image: "/payment-gateway-interface.png",
    description: "Sistem PPOB lengkap dengan berbagai provider pembayaran",
    features: ["Multi Provider", "Real-time Transaction", "Admin Dashboard", "API Integration"],
    stock: 15,
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 5,
    name: "Tools SEO Analyzer",
    category: "Utilities",
    price: 125000,
    originalPrice: 175000,
    image: "/seo-analysis-dashboard.png",
    description: "Tools analisis SEO lengkap untuk optimasi website",
    features: ["Keyword Analysis", "Backlink Checker", "Site Audit", "Competitor Analysis"],
    stock: 30,
    rating: 4.5,
    reviews: 123,
  },
  {
    id: 6,
    name: "Script E-commerce",
    category: "Script",
    price: 250000,
    originalPrice: 350000,
    image: "/ecommerce-platform-interface.png",
    description: "Script toko online lengkap dengan payment gateway",
    features: ["Multi Vendor", "Payment Gateway", "Inventory Management", "Mobile App"],
    stock: 20,
    rating: 4.8,
    reviews: 98,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Ahmad Rizki",
    role: "CEO Startup Tech",
    image: "/professional-businessman-portrait.png",
    quote: "Pelayanan sangat memuaskan! Website yang dibuat sangat profesional dan sesuai dengan kebutuhan bisnis kami.",
    rating: 5,
  },
  {
    id: 2,
    name: "Sari Dewi",
    role: "Online Shop Owner",
    image: "/professional-businesswoman-portrait.png",
    quote: "Script bot WhatsApp yang dibeli sangat membantu otomasi bisnis online saya. Highly recommended!",
    rating: 5,
  },
  {
    id: 3,
    name: "Budi Santoso",
    role: "Digital Marketer",
    image: "/digital-marketing-professional-portrait.jpg",
    quote: "Tools SEO yang disediakan sangat lengkap dan mudah digunakan. Sangat membantu dalam optimasi website klien.",
    rating: 5,
  },
  {
    id: 4,
    name: "Maya Putri",
    role: "Freelancer",
    image: "/freelancer-woman-portrait.jpg",
    quote: "Hosting yang stabil dan support yang responsif. Sudah 2 tahun menggunakan layanan ini tanpa masalah.",
    rating: 5,
  },
]